# Generated by Django 6.1.1 on 2026-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership'),
        ),
    ]
