# Generated by Django 6.1.1 on 2026-10-01 20:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmgmt', '0006_alter_task_due_date_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2026, 10, 1))]),
        ),
    ]
